#!/system/bin/sh
# cphelps76
# - sysctl -p
#

#Set governor items
echo 204000 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq;
echo 1600000 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq;
echo "interactive" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor;
echo "interactive" > /sys/devices/system/cpu/cpu1/cpufreq/scaling_governor;
echo "interactive" > /sys/devices/system/cpu/cpu2/cpufreq/scaling_governor;
echo "interactive" > /sys/devices/system/cpu/cpu3/cpufreq/scaling_governor;
